name: SimpleBan
version: '${project.version}'
main: dev.michaelh.simpleban.SimpleBan
api-version: 1.20
authors: [ MichaelH ]

commands:
  ban:
    description: Ban a player from the server.
    usage: /<command> <player> [reason]
    permission: simpleban.mod.ban
  unban:
    description: Unban a player from the server.
    usage: /<command> <player>
    permission: simpleban.mod.unban